shiketai_tool/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  
  resources :subjects do
    resources :blackboards
  end

end

shiketai_tool/app/models/blackboard.rb
class Blackboard < ActiveRecord::Base
    belongs_to :subject
    has_attached_file :material, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default/material.png"
	validates_attachment_content_type :material, :content_type => /\Aimage\/.*\Z/
	validates :title, presence:true
	validates_attachment :material, presence:true
end

shiketai_tool/app/models/day_of_a_week.rb
class DayOfAWeek < ActiveRecord::Base
end

shiketai_tool/app/models/period.rb
class Period < ActiveRecord::Base
end

shiketai_tool/app/models/semester.rb
class Semester < ActiveRecord::Base
end

shiketai_tool/app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :blackboards, dependent: :destroy
  validates :subject_name, presence: true
  validates :teacher, presence: true
  validates :period, presence: true
  validates :semester, presence:true
  validates :day_of_a_week, presence: true
  validates :description, presence: true
end

shiketai_tool/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

shiketai_tool/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

shiketai_tool/app/controllers/blackboards_controller.rb
class BlackboardsController < ApplicationController
  def new
	@subject = Subject.find(params[:subject_id])
    @blackboard = @subject.blackboards.new
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @blackboard = @subject.blackboards.create(blackboard_params)
	if @blackboard.save
	   redirect_to subject_path(@subject)
	else
	   render 'new'
	end
  end

  def show
    @subject = Subject.find(params[:subject_id])
    @blackboard = Blackboard.find(params[:id])
  end

  def edit
    @subject = Subject.find(params[:subject_id])
    @blackboard = @subject.blackboards.find(params[:id])
  end
  
  def update
    @subject = Subject.find(params[:subject_id])
    @blackboard = @subject.blackboards.find(params[:id])
	if @blackboard.update(blackboard_params)
	   redirect_to subject_path(@subject)
	else
	   render 'edit'
	end
  end

  def destroy
    @subject = Subject.find(params[:subject_id])
    @blackboard = @subject.blackboards.find(params[:id])
	@blackboard.destroy
	redirect_to subject_path(@subject)
  end

  private
    def blackboard_params
	  params.require(:blackboard).permit(:title, :description, :material, :subject_id, :deadline)
	end
end

shiketai_tool/app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
  end
end

shiketai_tool/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
	if @subject.save
	  redirect_to @subject
	else
	  render 'new'
	end
  end
  
  def show
    @subject = Subject.find(params[:id])
  end

  def index
    @subjects = Subject.all
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
	if @subject.update(subject_params)
	  redirect_to @subject
	else
	  render 'edit'
	end
  end
  
  def destroy
    @subject = Subject.find(params[:id])
	@subject.destroy
	redirect_to subjects_path
  end

  private
    def subject_params
	  params.require(:subject).permit(:subject_name, :teacher, :day_of_a_week, :period, :semester, :description)
	end
end

shiketai_tool/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @blackboards = Blackboard.all
	gon.blackboards = @blackboards

  end
end

shiketai_tool/app/helpers/application_helper.rb
module ApplicationHelper
end

shiketai_tool/app/helpers/blackboards_helper.rb
module BlackboardsHelper
end

shiketai_tool/app/helpers/calendar_helper.rb
module CalendarHelper
end

shiketai_tool/app/helpers/subjects_helper.rb
module SubjectsHelper
end

shiketai_tool/app/helpers/welcome_helper.rb
module WelcomeHelper
end

shiketai_tool/app/views/blackboards/_blackboards.html.erb
<h3>【資料一覧】</h3>
  <table class="table table-striped">
    <tr>
	  <th>板書</th>
	  <th>タイトル</th>
	  <th>説明</th>
	  <th>備考</th>
	  <th colspan="2"></th>
    </tr>
    <% @subject.blackboards.each do |blackboard| %>
    <tr>
	  <td><%= image_tag blackboard.material.url(:thumb) %></td>
	  <td><%= link_to blackboard.title, subject_blackboard_path(@subject, blackboard) %></td>
	  <td><%= blackboard.description %></td>
	  <td><%= blackboard.deadline %></td>
	  <td><%= link_to '編集', edit_subject_blackboard_path(@subject, blackboard) %></td>
	  <td><%= link_to '削除', subject_blackboard_path(@subject, blackboard), 
	          method: :delete, 
			  data: { confirm: '本当によろしいですか？' } 
		  %></td>

    </tr>
    <% end %>
  </table>

shiketai_tool/app/views/blackboards/_form.html.erb
  <% require "date" %>
  <%= form_for [@subject, @subject.blackboards.build], html:{multipart:true} do |f| %>
    <% if @blackboard.errors.any? %>
    <div id="error_explanation">
      <h2> 入力内容が適切ではありません。</h2>
      <ul>
      <% @blackboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
	<% end %>
	<br>
    <p>
      <%= f.label :title , "タイトル" %>
      <%= f.text_field :title %>
    </p>
 
    <p>
      <%= f.label :description , "説明" %>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.label :deadline , "締め切り" %>
      <%= f.datetime_select :deadline , default:DateTime.now+1 %>
    </p>
    
	<p>
      <%= f.label :material ,"板書データ"%><br>
      <%= f.file_field :material %>
    </p>
 
    <p>
      <%= f.submit %>
    </p>
<% end %>

shiketai_tool/app/views/blackboards/edit.html.erb
<h1>板書内容の編集</h1>
<%= render 'form' %>
<%= link_to '教科ページに戻る', subject_path(@subject) %>

shiketai_tool/app/views/blackboards/new.html.erb
<h1>新しく板書を登録する</h1>
<%= render 'form' %>
<%= link_to '教科ページに戻る', subject_path(@subject) %>

shiketai_tool/app/views/blackboards/show.html.erb
<h1><%= @blackboard.title %></h1>
<blockquote>
  <%= @blackboard.description %>
</blockquote>

<%= link_to  @blackboard.material.url(:original, false) do %>
   <button class="btn-large btn-primary">ダウンロード</button>
<% end %>
<br><br>

<%= image_tag @blackboard.material.url(:original) %><br>
<%= link_to "教科ページに戻る", subject_path(@subject) %><br>

shiketai_tool/app/views/calendar/index.html.erb
<h1>Calendar#index</h1>
<p>Find me in app/views/calendar/index.html.erb</p>

shiketai_tool/app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        	<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<%= link_to "SHIKETAI TOOL", root_path, class:"navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      　<li>
	       <%= link_to root_path do %>
		     <i class="glyphicon glyphicon-home">ホーム</i>
		   <% end %>
	    </li>
      　<li>
	       <%= link_to subjects_path do %>
		     <i class="glyphicon glyphicon-book">科目一覧</i>
		   <% end %>
	    </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
     	   <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
      </form>


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="font-size:24px"><span class="glyphicon glyphicon-user"></span>My menu<b class="caret"></b></a>
          <ul class="dropdown-menu">
	        <% if user_signed_in? %>
                  <li><i class="glyphicon glyphicon-user"><%= current_user.email %></i></li>
	          
	          <li><%= link_to 'プロフィールの編集', edit_user_registration_path, class: 'navbar-link' %></li> 
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
	        <% else %>
	          <li><%= link_to "サインアップ", new_user_registration_path, class: 'navbar-link' %></li> 
	          <li><%= link_to "ログイン", new_user_session_path, class: 'navbar-link' %></li>
	        <% end %>
          </ul>
        </li>
      </ul>


      <p class="navbar-text pull-right">
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>

shiketai_tool/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShiketaiTool</title>
  
  <link href="http://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet"> 
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> 
  <%= csrf_meta_tags %>
</head>
<body style ="padding-top:71px">
   <%= render partial: 'layouts/header' %>
  <div id="main" class="container">
    <div class="row">
      <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
      <% end %>

      <%= yield %>

    </div>
  </div>
</body>
</html>

shiketai_tool/app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
  <% if @subject.errors.any? %>
  <div id="error_explanation">
    <h2>入力内容が適切ではありません。</h2>
    <ul>
    <% @subject.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <br>
  <p>
    <%= f.label :subject_name , "科目名" %>
    <%= f.text_field :subject_name %>
  </p>
 
  <p>
    <%= f.label :teacher , "教員" %>
    <%= f.text_field :teacher %>
  </p>

  <p>
    <%= f.label :day_of_a_week , "曜日" %>
    <%= f.collection_select :day_of_a_week, DayOfAWeek.all, :day_of_a_week, :day_of_a_week %>
  <p>
  
  <p>
    <%= f.label :period , "時限" %>
    <%= f.collection_select :period, Period.all, :period, :period %>
  <p>
  
  <p>
    <%= f.label :semester , "学期" %>
    <%= f.collection_select :semester, Semester.all, :semester, :semester %>
  <p>
  
  <p>
    <%= f.label :description, "説明" %>
    <%= f.text_area :description %>
  <p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

shiketai_tool/app/views/subjects/edit.html.erb
<h1>教科情報の編集</h1>
 <%= render 'form' %>
<%= link_to '教科一覧に戻る', subjects_path %>

shiketai_tool/app/views/subjects/index.html.erb
<h1>科目一覧</h1>
<br>
<%= link_to  new_subject_path do %>
  <button class="btn btn-primary">新しい科目の登録</button>
<% end %>
<br><br>

<table class="table table-primary table-striped" >
  <tr>
    <th>科目名</th>
	<th>教員名</th>
    <th>曜日</th>
    <th>時限</th>
	<th>学期</th>
	<th>説明</th>
	<th colspan="2"></th>
  </tr>
  <% @subjects.each do |subject|  %>
  <tr>
    <td><%= link_to subject.subject_name, subject_path(subject) %></td> 
    <td><%= subject.teacher %></td> 
    <td><%= subject.day_of_a_week %></td> 
    <td><%= subject.period %></td> 
    <td><%= subject.semester %></td> 
    <td><%= subject.description %></td> 
	<td><%= link_to '編集', edit_subject_path(subject) %></td>
	<td><%= link_to '削除', subject_path(subject),
	        method: :delete, data: { confirm: '本当によろしいですか？' } %></td>
  </tr>
  <% end %>
</table>

shiketai_tool/app/views/subjects/new.html.erb
<h1>新しく科目を登録する</h1>
<%= render 'form' %>
<%= link_to '教科一覧に戻る', subjects_path %>

shiketai_tool/app/views/subjects/show.html.erb
<h1><%= @subject.subject_name%></h1>
<h3>担当教員: <%= @subject.teacher %></h3>
<%= @subject.semester %>　|　<%= @subject.day_of_a_week %>　|　<%= @subject.period %><br><br>

<h4><%= @subject.description %></h4>
<br>
<%= link_to  new_subject_blackboard_path(@subject.id) do %>
  <button class="btn btn-primary">板書のアップロード</button>
<% end %>
<br>
<br>
<%= render "blackboards/blackboards" %>
<br><br>
<%= link_to "教科情報を編集する", edit_subject_path %>|
<%= link_to "科目一覧に戻る", subjects_path %>

shiketai_tool/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規ユーザー登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れてしまった方はこちら", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

shiketai_tool/app/views/welcome/index.html.erb
<div id=calendar></div>